/**
 * Language Context - Manages language state and translations
 */

import React, { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation strings
const translations = {
  en: {
    settings: 'Settings',
    manageAccount: 'Manage your account settings and preferences',
    account: 'Account',
    email: 'Email',
    password: 'Password',
    change: 'Change',
    appearance: 'Appearance',
    theme: 'Theme',
    chooseTheme: 'Choose your preferred theme',
    notifications: 'Notifications',
    emailNotifications: 'Email Notifications',
    receiveEmailNotifications: 'Receive notifications via email',
    pushNotifications: 'Push Notifications',
    receivePushNotifications: 'Receive push notifications',
    productUpdates: 'Product Updates',
    getNotified: 'Get notified about new features and updates',
    general: 'General',
    language: 'Language',
    selectLanguage: 'Select your preferred language',
    autoBackup: 'Auto Backup',
    autoBackupDesc: 'Automatically backup your files',
    privacy: 'Privacy',
    dataSharing: 'Data Sharing',
    dataSharingDesc: 'Help improve our service by sharing usage data',
    downloadHistory: 'Download History',
    downloadHistoryDesc: 'Keep track of your download history',
    changeEmail: 'Change Email',
    changePassword: 'Change Password',
    newEmail: 'New Email',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    save: 'Save',
    cancel: 'Cancel',
    close: 'Close',
    lastChanged: 'Last changed: Never',
    lastChangedJustNow: 'Last changed: Just now',
    lastChangedMinutesAgo: 'Last changed: {minutes} minute(s) ago',
    lastChangedHoursAgo: 'Last changed: {hours} hour(s) ago',
    lastChangedYesterday: 'Last changed: Yesterday',
    lastChangedDaysAgo: 'Last changed: {days} days ago',
    lastChangedWeeksAgo: 'Last changed: {weeks} week(s) ago',
    lastChangedOn: 'Last changed on',
    backToDashboard: 'Back to Dashboard',
    fillAllFields: 'Please fill in all fields',
    invalidEmail: 'Please enter a valid email address',
    emailChangedSuccess: 'Email changed successfully!',
    emailChangeFailed: 'Failed to change email. Please try again.',
    passwordsDoNotMatch: 'New passwords do not match',
    passwordMinLength: 'Password must be at least 6 characters long',
    passwordChangedSuccess: 'Password changed successfully!',
    passwordChangeFailed: 'Failed to change password. Please check your current password.',
  },
  hi: {
    settings: 'सेटिंग्स',
    manageAccount: 'अपनी खाता सेटिंग्स और प्राथमिकताएं प्रबंधित करें',
    account: 'खाता',
    email: 'ईमेल',
    password: 'पासवर्ड',
    change: 'बदलें',
    appearance: 'दिखावट',
    theme: 'थीम',
    chooseTheme: 'अपनी पसंदीदा थीम चुनें',
    notifications: 'सूचनाएं',
    emailNotifications: 'ईमेल सूचनाएं',
    receiveEmailNotifications: 'ईमेल के माध्यम से सूचनाएं प्राप्त करें',
    pushNotifications: 'पुश सूचनाएं',
    receivePushNotifications: 'पुश सूचनाएं प्राप्त करें',
    productUpdates: 'उत्पाद अपडेट',
    getNotified: 'नई सुविधाओं और अपडेट के बारे में सूचित रहें',
    general: 'सामान्य',
    language: 'भाषा',
    selectLanguage: 'अपनी पसंदीदा भाषा चुनें',
    autoBackup: 'स्वचालित बैकअप',
    autoBackupDesc: 'अपनी फ़ाइलों का स्वचालित रूप से बैकअप लें',
    privacy: 'गोपनीयता',
    dataSharing: 'डेटा साझाकरण',
    dataSharingDesc: 'उपयोग डेटा साझा करके हमारी सेवा में सुधार करने में मदद करें',
    downloadHistory: 'डाउनलोड इतिहास',
    downloadHistoryDesc: 'अपने डाउनलोड इतिहास का ट्रैक रखें',
    changeEmail: 'ईमेल बदलें',
    changePassword: 'पासवर्ड बदलें',
    newEmail: 'नया ईमेल',
    currentPassword: 'वर्तमान पासवर्ड',
    newPassword: 'नया पासवर्ड',
    confirmPassword: 'पासवर्ड की पुष्टि करें',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    close: 'बंद करें',
    lastChanged: 'अंतिम बदला गया: कभी नहीं',
    lastChangedJustNow: 'अंतिम बदला गया: अभी',
    lastChangedMinutesAgo: 'अंतिम बदला गया: {minutes} मिनट पहले',
    lastChangedHoursAgo: 'अंतिम बदला गया: {hours} घंटे पहले',
    lastChangedYesterday: 'अंतिम बदला गया: कल',
    lastChangedDaysAgo: 'अंतिम बदला गया: {days} दिन पहले',
    lastChangedWeeksAgo: 'अंतिम बदला गया: {weeks} सप्ताह पहले',
    lastChangedOn: 'अंतिम बदला गया',
    backToDashboard: 'डैशबोर्ड पर वापस जाएं',
    fillAllFields: 'कृपया सभी फ़ील्ड भरें',
    invalidEmail: 'कृपया एक वैध ईमेल पता दर्ज करें',
    emailChangedSuccess: 'ईमेल सफलतापूर्वक बदला गया!',
    emailChangeFailed: 'ईमेल बदलने में विफल। कृपया पुनः प्रयास करें।',
    passwordsDoNotMatch: 'नए पासवर्ड मेल नहीं खाते',
    passwordMinLength: 'पासवर्ड कम से कम 6 वर्ण लंबा होना चाहिए',
    passwordChangedSuccess: 'पासवर्ड सफलतापूर्वक बदला गया!',
    passwordChangeFailed: 'पासवर्ड बदलने में विफल। कृपया अपना वर्तमान पासवर्ड जांचें।',
  },
  es: {
    settings: 'Configuración',
    manageAccount: 'Administra la configuración y preferencias de tu cuenta',
    account: 'Cuenta',
    email: 'Correo electrónico',
    password: 'Contraseña',
    change: 'Cambiar',
    appearance: 'Apariencia',
    theme: 'Tema',
    chooseTheme: 'Elige tu tema preferido',
    notifications: 'Notificaciones',
    emailNotifications: 'Notificaciones por correo',
    receiveEmailNotifications: 'Recibir notificaciones por correo electrónico',
    pushNotifications: 'Notificaciones push',
    receivePushNotifications: 'Recibir notificaciones push',
    productUpdates: 'Actualizaciones del producto',
    getNotified: 'Recibe notificaciones sobre nuevas funciones y actualizaciones',
    general: 'General',
    language: 'Idioma',
    selectLanguage: 'Selecciona tu idioma preferido',
    autoBackup: 'Copia de seguridad automática',
    autoBackupDesc: 'Hacer copia de seguridad automática de tus archivos',
    privacy: 'Privacidad',
    dataSharing: 'Compartir datos',
    dataSharingDesc: 'Ayuda a mejorar nuestro servicio compartiendo datos de uso',
    downloadHistory: 'Historial de descargas',
    downloadHistoryDesc: 'Mantén un registro de tu historial de descargas',
    changeEmail: 'Cambiar correo electrónico',
    changePassword: 'Cambiar contraseña',
    newEmail: 'Nuevo correo electrónico',
    currentPassword: 'Contraseña actual',
    newPassword: 'Nueva contraseña',
    confirmPassword: 'Confirmar contraseña',
    save: 'Guardar',
    cancel: 'Cancelar',
    close: 'Cerrar',
    lastChanged: 'Último cambio: Nunca',
    lastChangedJustNow: 'Último cambio: Ahora mismo',
    lastChangedMinutesAgo: 'Último cambio: Hace {minutes} minuto(s)',
    lastChangedHoursAgo: 'Último cambio: Hace {hours} hora(s)',
    lastChangedYesterday: 'Último cambio: Ayer',
    lastChangedDaysAgo: 'Último cambio: Hace {days} días',
    lastChangedWeeksAgo: 'Último cambio: Hace {weeks} semana(s)',
    lastChangedOn: 'Último cambio el',
    backToDashboard: 'Volver al panel',
    fillAllFields: 'Por favor complete todos los campos',
    invalidEmail: 'Por favor ingrese una dirección de correo válida',
    emailChangedSuccess: '¡Correo electrónico cambiado exitosamente!',
    emailChangeFailed: 'Error al cambiar el correo electrónico. Por favor intente de nuevo.',
    passwordsDoNotMatch: 'Las nuevas contraseñas no coinciden',
    passwordMinLength: 'La contraseña debe tener al menos 6 caracteres',
    passwordChangedSuccess: '¡Contraseña cambiada exitosamente!',
    passwordChangeFailed: 'Error al cambiar la contraseña. Por favor verifique su contraseña actual.',
  },
  fr: {
    settings: 'Paramètres',
    manageAccount: 'Gérez les paramètres et préférences de votre compte',
    account: 'Compte',
    email: 'E-mail',
    password: 'Mot de passe',
    change: 'Changer',
    appearance: 'Apparence',
    theme: 'Thème',
    chooseTheme: 'Choisissez votre thème préféré',
    notifications: 'Notifications',
    emailNotifications: 'Notifications par e-mail',
    receiveEmailNotifications: 'Recevoir des notifications par e-mail',
    pushNotifications: 'Notifications push',
    receivePushNotifications: 'Recevoir des notifications push',
    productUpdates: 'Mises à jour du produit',
    getNotified: 'Soyez informé des nouvelles fonctionnalités et mises à jour',
    general: 'Général',
    language: 'Langue',
    selectLanguage: 'Sélectionnez votre langue préférée',
    autoBackup: 'Sauvegarde automatique',
    autoBackupDesc: 'Sauvegarder automatiquement vos fichiers',
    privacy: 'Confidentialité',
    dataSharing: 'Partage de données',
    dataSharingDesc: 'Aidez à améliorer notre service en partageant les données d\'utilisation',
    downloadHistory: 'Historique des téléchargements',
    downloadHistoryDesc: 'Gardez une trace de votre historique de téléchargements',
    changeEmail: 'Changer l\'e-mail',
    changePassword: 'Changer le mot de passe',
    newEmail: 'Nouvel e-mail',
    currentPassword: 'Mot de passe actuel',
    newPassword: 'Nouveau mot de passe',
    confirmPassword: 'Confirmer le mot de passe',
    save: 'Enregistrer',
    cancel: 'Annuler',
    close: 'Fermer',
    lastChanged: 'Dernière modification : Jamais',
    lastChangedJustNow: 'Dernière modification : À l\'instant',
    lastChangedMinutesAgo: 'Dernière modification : Il y a {minutes} minute(s)',
    lastChangedHoursAgo: 'Dernière modification : Il y a {hours} heure(s)',
    lastChangedYesterday: 'Dernière modification : Hier',
    lastChangedDaysAgo: 'Dernière modification : Il y a {days} jours',
    lastChangedWeeksAgo: 'Dernière modification : Il y a {weeks} semaine(s)',
    lastChangedOn: 'Dernière modification le',
    backToDashboard: 'Retour au tableau de bord',
    fillAllFields: 'Veuillez remplir tous les champs',
    invalidEmail: 'Veuillez entrer une adresse e-mail valide',
    emailChangedSuccess: 'E-mail modifié avec succès !',
    emailChangeFailed: 'Échec de la modification de l\'e-mail. Veuillez réessayer.',
    passwordsDoNotMatch: 'Les nouveaux mots de passe ne correspondent pas',
    passwordMinLength: 'Le mot de passe doit contenir au moins 6 caractères',
    passwordChangedSuccess: 'Mot de passe modifié avec succès !',
    passwordChangeFailed: 'Échec de la modification du mot de passe. Veuillez vérifier votre mot de passe actuel.',
  },
  de: {
    settings: 'Einstellungen',
    manageAccount: 'Verwalten Sie Ihre Kontoeinstellungen und Präferenzen',
    account: 'Konto',
    email: 'E-Mail',
    password: 'Passwort',
    change: 'Ändern',
    appearance: 'Erscheinungsbild',
    theme: 'Thema',
    chooseTheme: 'Wählen Sie Ihr bevorzugtes Thema',
    notifications: 'Benachrichtigungen',
    emailNotifications: 'E-Mail-Benachrichtigungen',
    receiveEmailNotifications: 'Benachrichtigungen per E-Mail erhalten',
    pushNotifications: 'Push-Benachrichtigungen',
    receivePushNotifications: 'Push-Benachrichtigungen erhalten',
    productUpdates: 'Produkt-Updates',
    getNotified: 'Über neue Funktionen und Updates informiert werden',
    general: 'Allgemein',
    language: 'Sprache',
    selectLanguage: 'Wählen Sie Ihre bevorzugte Sprache',
    autoBackup: 'Automatische Sicherung',
    autoBackupDesc: 'Automatisches Backup Ihrer Dateien',
    privacy: 'Datenschutz',
    dataSharing: 'Datenaustausch',
    dataSharingDesc: 'Helfen Sie, unseren Service zu verbessern, indem Sie Nutzungsdaten teilen',
    downloadHistory: 'Download-Verlauf',
    downloadHistoryDesc: 'Behalten Sie Ihren Download-Verlauf im Auge',
    changeEmail: 'E-Mail ändern',
    changePassword: 'Passwort ändern',
    newEmail: 'Neue E-Mail',
    currentPassword: 'Aktuelles Passwort',
    newPassword: 'Neues Passwort',
    confirmPassword: 'Passwort bestätigen',
    save: 'Speichern',
    cancel: 'Abbrechen',
    close: 'Schließen',
    lastChanged: 'Zuletzt geändert: Nie',
    lastChangedJustNow: 'Zuletzt geändert: Gerade eben',
    lastChangedMinutesAgo: 'Zuletzt geändert: Vor {minutes} Minute(n)',
    lastChangedHoursAgo: 'Zuletzt geändert: Vor {hours} Stunde(n)',
    lastChangedYesterday: 'Zuletzt geändert: Gestern',
    lastChangedDaysAgo: 'Zuletzt geändert: Vor {days} Tagen',
    lastChangedWeeksAgo: 'Zuletzt geändert: Vor {weeks} Woche(n)',
    lastChangedOn: 'Zuletzt geändert am',
    backToDashboard: 'Zurück zum Dashboard',
    fillAllFields: 'Bitte füllen Sie alle Felder aus',
    invalidEmail: 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
    emailChangedSuccess: 'E-Mail erfolgreich geändert!',
    emailChangeFailed: 'E-Mail-Änderung fehlgeschlagen. Bitte versuchen Sie es erneut.',
    passwordsDoNotMatch: 'Die neuen Passwörter stimmen nicht überein',
    passwordMinLength: 'Das Passwort muss mindestens 6 Zeichen lang sein',
    passwordChangedSuccess: 'Passwort erfolgreich geändert!',
    passwordChangeFailed: 'Passwortänderung fehlgeschlagen. Bitte überprüfen Sie Ihr aktuelles Passwort.',
  },
};

export const LanguageProvider = ({ children }) => {
  // Get language from localStorage or default to 'en'
  const [language, setLanguage] = useState(() => {
    const savedLanguage = localStorage.getItem('language');
    return savedLanguage || 'en';
  });

  useEffect(() => {
    // Save language to localStorage
    localStorage.setItem('language', language);
    // Set HTML lang attribute
    document.documentElement.setAttribute('lang', language);
  }, [language]);

  const t = (key) => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  const value = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
